# Basic site info
title: Burp Suite Professional macOS
description: One-click Burp Suite Pro installer for macOS

# Use remote theme
plugins:
  - jekyll-remote-theme

remote_theme: "mmistakes/minimal-mistakes"

# GitHub Pages settings
baseurl: ""
url: "https://rexiop.github.io"
