title: Burp Suite Professional macOS
description: One-click Burp Suite Pro installer for macOS
baseurl: "" # leave empty for root
url: "https://rexiop.github.io"
theme: minimal-mistakes-jekyll
plugins:
  - jekyll-remote-theme
remote_theme: mmistakes/minimal-mistakes
